// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LaundrySystem.UI.Entities
{
    public partial class tblCustomer
    {
        [Key]
        public Guid CustomerID { get; set; }
        [StringLength(50)]
        public string CustomerName { get; set; }
        [StringLength(50)]
        public string PhoneNo { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        public string Address { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AddedDate { get; set; }
        [StringLength(5)]
        public string CustomerNo { get; set; }
    }
}