// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LaundrySystem.UI.Entities
{
    public partial class tblService
    {
        [Key]
        public Guid ServiceId { get; set; }
        public string ServiceName { get; set; }
        public string ServiceImage { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AddedDate { get; set; }
        public Guid? CreatedBy { get; set; }
    }
}