// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LaundrySystem.UI.Entities
{
    public partial class tblSale
    {
        [Key]
        public Guid SaleId { get; set; }
        [StringLength(50)]
        public string SaleNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SaleDate { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? SaleTotal { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Discount { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Tax { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? NetTotal { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Balance { get; set; }
        public Guid? CustomerId { get; set; }
        public Guid? UserId { get; set; }
        [StringLength(100)]
        public string FullName { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(100)]
        public string Address { get; set; }
        [StringLength(100)]
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? TotalPlusDelivery { get; set; }
        public Guid? OrderStatusID { get; set; }
        [StringLength(500)]
        public string OrderStatusName { get; set; }
    }
}