// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LaundrySystem.UI.Entities
{
    public partial class tblShoppingCartItem
    {
        [Key]
        public Guid ShoppingCartItemID { get; set; }
        public int? Quantity { get; set; }
        public Guid? ProductID { get; set; }
        public string ShoppingCartID { get; set; }
        public Guid? ProductQtyID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
    }
}