// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LaundrySystem.UI.Entities
{
    public partial class tblStatus
    {
        [Key]
        public Guid StatusID { get; set; }
        [StringLength(1000)]
        public string StatusName { get; set; }
    }
}